-- 02_create_tables.sql
-- 你现在应该已经在：TRAINING_DB.UMKC_RAG
-- （如果不确定，可以先跑：SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();）
USE WAREHOUSE LEARNER_WH;
USE DATABASE TRAINING_DB;
USE SCHEMA UMKC_RAG;

-- 1) 文档元信息表：每个 PDF 一行
CREATE TABLE IF NOT EXISTS DOCS (
  DOC_ID STRING DEFAULT UUID_STRING(),
  DOC_NAME STRING NOT NULL,
  DOC_SOURCE STRING,
  DOC_TYPE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DOCS PRIMARY KEY (DOC_ID)
);

-- 2) 文档切块表：每个 chunk 一行
CREATE TABLE IF NOT EXISTS DOC_CHUNKS (
  DOC_ID STRING NOT NULL,
  CHUNK_ID INTEGER NOT NULL,
  CHUNK_TEXT STRING NOT NULL,
  PAGE_NUM INTEGER,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DOC_CHUNKS PRIMARY KEY (DOC_ID, CHUNK_ID)
);

-- 3) Embedding 特征表：每个 chunk 一行 embedding
-- 注意：EMBEDDING 用 ARRAY 存（后面 Python 写回会用到）
CREATE TABLE IF NOT EXISTS CHUNK_EMBEDDINGS (
  DOC_ID STRING NOT NULL,
  CHUNK_ID INTEGER NOT NULL,
  EMBEDDING ARRAY NOT NULL,
  EMBEDDING_MODEL STRING NOT NULL,
  EMBEDDING_VERSION STRING NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_CHUNK_EMBEDDINGS PRIMARY KEY (DOC_ID, CHUNK_ID, EMBEDDING_MODEL, EMBEDDING_VERSION)
);

-- 4) Pipeline 日志表：记录 ingestion / embedding / query 等运行情况
CREATE TABLE IF NOT EXISTS PIPELINE_LOGS (
  RUN_ID STRING NOT NULL,
  STAGE STRING NOT NULL,
  STATUS STRING NOT NULL,
  ROWS_IN INTEGER,
  ROWS_OUT INTEGER,
  LATENCY_MS INTEGER,
  ERROR_MESSAGE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);